-- Tabla para registrar asistencia diaria por alumno.
create table if not exists public.asistencias (
	id bigint generated by default as identity primary key,
	maestro_id uuid not null references auth.users(id) on delete cascade,
	grupo_id uuid not null references public.grupos(id) on delete cascade,
	alumno_id uuid not null references public.alumnos(id) on delete cascade,
	fecha date not null,
	asistio boolean not null default false,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now(),
	unique (grupo_id, alumno_id, fecha)
);

create index if not exists asistencias_maestro_fecha_idx
	on public.asistencias (maestro_id, fecha);

create index if not exists asistencias_grupo_fecha_idx
	on public.asistencias (grupo_id, fecha);

-- Trigger para mantener updated_at.
create or replace function public.set_asistencias_updated_at()
returns trigger
language plpgsql
as $$
begin
	new.updated_at = now();
	return new;
end;
$$;

drop trigger if exists trg_asistencias_updated_at on public.asistencias;
create trigger trg_asistencias_updated_at
before update on public.asistencias
for each row
execute function public.set_asistencias_updated_at();

alter table public.asistencias enable row level security;

-- Cada docente solo ve sus propios registros.
drop policy if exists asistencias_select_own on public.asistencias;
create policy asistencias_select_own
on public.asistencias
for select
using (auth.uid() = maestro_id);

-- Cada docente solo inserta para su propio maestro_id.
drop policy if exists asistencias_insert_own on public.asistencias;
create policy asistencias_insert_own
on public.asistencias
for insert
with check (auth.uid() = maestro_id);

-- Cada docente solo actualiza sus propios registros.
drop policy if exists asistencias_update_own on public.asistencias;
create policy asistencias_update_own
on public.asistencias
for update
using (auth.uid() = maestro_id)
with check (auth.uid() = maestro_id);

-- Opcional: permitir borrado propio si en algun momento lo necesitas.
drop policy if exists asistencias_delete_own on public.asistencias;
create policy asistencias_delete_own
on public.asistencias
for delete
using (auth.uid() = maestro_id);
